<?php
namespace Hostnet\Component\AccessorGenerator\AnnotationProcessor;

use Hostnet\Component\AccessorGenerator\Annotation\Generate;

/**
 * Processes the @Generate annotation and determines which methods should be
 * generated by the code generator. Store everything in a PropertyInformation
 * object.
 *
 * @author Hidde Boomsma <hboomsma@hostnet.nl>
 */
class GenerateAnnotationProcessor implements AnnotationProcessorInterface
{
    /**
     * @see AnnotationProcessorInterface::processAnnotation()
     *
     * @param object              $annotation
     * @param PropertyInformation $info
     */
    public function processAnnotation($annotation, PropertyInformation $info)
    {
        // Only process Generate annotations.
        if (!$annotation instanceof Generate) {
            return;
        }

        if ($annotation->getEnumerators()) {
            $info->setEnumeratorsToGenerate($annotation->getEnumerators());
            $annotation->setDefaultVisibility(Generate::VISIBILITY_NONE);
        } else {
            $annotation->setDefaultVisibility(Generate::VISIBILITY_PUBLIC);
        }

        // By default no method is generated.
        //
        // Each processor can enforce a limitation on the generated methods.
        // If processor A lets a method be private, and processor B tells it to
        // be protected, it will end up private.

        $info->limitMaximumGetVisibility(
            Generate::getMostLimitedVisibility($annotation->getGet(), $annotation->getIs())
        );
        $info->limitMaximumSetVisibility(
            Generate::getMostLimitedVisibility($annotation->getSet())
        );
        $info->limitMaximumAddVisibility(
            Generate::getMostLimitedVisibility($annotation->getAdd(), $annotation->getSet())
        );
        $info->limitMaximumRemoveVisibility(
            Generate::getMostLimitedVisibility($annotation->getRemove(), $annotation->getSet())
        );

        null === $info->getType() && $annotation->getType() && $info->setType($annotation->getType());
        null !== $annotation->getType() && $info->setTypeHint($annotation->getType());
        null !== $annotation->getEncryptionAlias() && $info->setEncryptionAlias($annotation->getEncryptionAlias());

        // Enforce always
        $info->setGenerateStrict($annotation->isStrict());
    }

    /**
     * @see AnnotationProcessorInterface::getProcessableAnnotations()
     */
    public function getProcessableAnnotationNamespace()
    {
        return 'Hostnet\Component\AccessorGenerator\Annotation';
    }
}
