name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.3', '8.4']
        dependency-versions: ['highest', 'lowest']
    name: PHP ${{ matrix.php-versions }} (${{ matrix.dependency-versions }} deps)
    steps:
      -   uses: actions/checkout@v4
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
      -   name: Get composer cache directory
          id: composer-cache
          run: |
              echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      -   uses: actions/cache@v4
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ matrix.dependency-versions }}-${{ hashFiles('**/composer.lock') }}
            restore-keys: ${{ runner.os }}-composer-${{ matrix.dependency-versions }}-
      -   name: composer validate
          run: composer validate --strict
      -   name: composer install
          if: matrix.dependency-versions == 'highest'
          run: composer install --no-progress --prefer-dist --optimize-autoloader
      -   name: composer update --prefer-lowest
          if: matrix.dependency-versions == 'lowest'
          run: composer update --no-progress --prefer-dist --prefer-stable --prefer-lowest --optimize-autoloader
      -   name: phpunit
          run: php vendor/bin/phpunit
      -   name: phpcs
          run: php vendor/bin/phpcs
